# Starter pipeline



trigger:
- main



steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    #echo Add other tasks to build, test, and deploy your project.
    #echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: UiPathPack@2
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: 'C:\Users\Naveen Rana\Documents\UiPath\AdactinTesting\project.json'
    outputType: 'Process'
    orchestratorConnection: 'uiPath_Azure_Connection'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'

- task: UiPathDeploy@2
  inputs:
    orchestratorConnection: 'uiPath_Azure_Connection'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'Naveen'
    entryPoints: 'Main.xaml'
- task: UiPathRunJob@2
  inputs:
    orchestratorConnection: 'uiPath_Azure_Connection'
    processName: 'Adacitin Hotel Booking'
    folderName: 'Naveen'
    jobType: 'TestAutomation'
    user: 'testiuslhzpy'
    machine: 'txchd-lap-191'