trigger:
- main

pool: Default
 

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

stages:
  - stage: Build
    displayName: Build Package
    jobs:
    - job: BuildPackage
      pool: TXCHD-LAP-191
      steps:
        - task: UiPathRunJob@2
          inputs:
            orchestratorConnection: 'uiPath_Azure_Connection'
            processName: 'Adacitin Hotel Booking'
            folderName: 'Naveen'
            jobType: 'TestAutomation'
            user: 'txchd-lap-191\naveen rana'
            machine: 'txchd-lap-191'