trigger:
- main


 
stages:
  - stage: Build
    displayName: Build Package
    jobs:
    - job: BuildPackage
      pool: Default
      steps:
      - task: UiPathPack@2
        inputs:
          versionType: 'AutoVersion'
          outputType: 'Process'
          orchestratorConnection: 'uiPath_Azure_Connection'
          outputPath: '$(Build.ArtifactStagingDirectory)\Output'
      - publish: $(Build.ArtifactStagingDirectory)
        artifact: drop
  